### ISSUE TITLE
Stopping Phoenix does not stop nodejs

### ISSUE THREAD

**Issue by vestimir** [valo/phoenix_with_nextjs#7]
Steps to reproduce:

1. Add custom server.js with Express (https://learnnextjs.com/basics/server-side-support-for-clean-urls)
2. Change dev script to `node server.js`
3. Run server with `mix phx.server`
4. Stop server with `Ctrl+C`
5. `ps aux | grep node` still shows the node instance

Any ideas how to stop the node instance when phoenix is shut down?

**Comment by valo** [comment]
Start the node server like this: https://github.com/valo/phoenix_with_nextjs/blob/master/app/package.json#L12

Using the `exit_on_eof` node package should fix the issue.

**Comment by vestimir** [comment]
Works like a charm. Thanks! 

```js
"server": "node node_modules/exit_on_eof/index.js 'node server.js'",
```
